import type { JsonToolWorkspaceInput } from './createJsonToolWorkspaceProps';

export function createJsonToolPanesProps(input: JsonToolWorkspaceInput) {
  const {
    activeDocumentMeta,
    activeLargeRawViewerData,
    activeLargeViewerCollapsedLines,
    activeLargeViewerData,
    activeLeftMatchCount,
    activeRawText,
    activeRightMatchCount,
    activeRightPinnedPathItems,
    activeRightSelectedRange,
    activeTab,
    applyRightNodeMutationAtOffset,
    copyNodeDetailAtOffset,
    copyValueAtOffset,
    formattedValue,
    gotoNextLeft,
    gotoNextRight,
    gotoPrevLeft,
    gotoPrevRight,
    handleLeftChange,
    handleLeftMount,
    handleLeftSearchOptionsChange,
    handleLeftSearchTermChange,
    handleOpenEditNodeAtOffset,
    handleOpenUnescapedNodeAtOffset,
    handleRightMount,
    handleRightSearchOptionsChange,
    handleRightSearchTermChange,
    isBuildingDedicatedRightViewer,
    isDarkMode,
    isFormattingActiveTab,
    isImportingActiveTab,
    isLargeFileMode,
    isLeftFindOpen,
    isLeftSearchLoadingMore,
    isRightFindOpen,
    isRightSearchLoadingMore,
    largeRawViewerRef,
    largeViewerMatches,
    largeViewerRef,
    leftPaneMetaText,
    leftRawHighlightRange,
    leftReplaceText,
    leftSearchHasMore,
    leftSearchOptions,
    leftSearchTerm,
    loadMoreLeftSearch,
    loadMoreRightSearch,
    normalizedLeftMatchIndex,
    normalizedRightMatchIndex,
    openRightFind,
    pinActiveRightPath,
    processingStageText,
    rememberRightSearchTerm,
    replaceAllLeftMatches,
    replaceLeftMatch,
    requestWorkerLocate,
    rightMatchIndex,
    rightPaneMetaText,
    rightRecentSearches,
    rightSearchHasMore,
    rightSearchOptions,
    rightSearchTerm,
    selectRightPinnedPath,
    setIsRightFindOpen,
    setLargeViewerCollapsedLinesByTab,
    setLargeViewerMatchCount,
    setLeftReplaceText,
    setRightMatchIndex,
    setRightSearchTerm,
    shouldEnableRightPaneFolding,
    shouldUseDedicatedLeftViewer,
    shouldUseDedicatedRightViewer,
    t,
    wrapLongLines,
  } = input;

  return {
    activeLargeRawViewerData,
    activeLargeViewerCollapsedLines,
    activeLargeViewerData,
    activeLeftMatchCount,
    activeRawText,
    activeRightMatchCount,
    formattedValue,
    isBuildingDedicatedRightViewer,
    isDarkMode,
    isFormattingActiveTab,
    isImportingActiveTab,
    isLargeFileMode,
    isLeftFindOpen,
    isRightFindOpen,
    largeRawViewerRef,
    largeViewerMatches,
    largeViewerRef,
    leftPaneMetaText,
    leftRawHighlightRange,
    leftReplaceText,
    leftSearchHasMore,
    leftSearchOptions,
    leftSearchTerm,
    normalizedLeftMatchIndex,
    normalizedRightMatchIndex,
    processingStageText,
    rightMatchIndex,
    rightPaneMetaText,
    rightPinnedPaths: activeRightPinnedPathItems,
    rightRecentSearches,
    rightSearchHasMore,
    rightSearchOptions,
    rightSelectedRange: activeRightSelectedRange,
    rightSearchTerm,
    shouldEnableRightPaneFolding,
    shouldShowLeftPlaceholder: activeDocumentMeta.rawLength === 0 && !isImportingActiveTab,
    shouldUseDedicatedLeftViewer,
    shouldUseDedicatedRightViewer,
    wrapLongLines,
    isLeftSearchLoadingMore,
    isRightSearchLoadingMore,
    onCloseLeftFind: input.closeLeftFind,
    onCloseRightFind: input.closeRightFind,
    onCopyRightCompactJson: (offset: number) => copyNodeDetailAtOffset(activeTab.id, offset, true, 'compact-json'),
    onCopyRightFormattedJson: (offset: number) => copyNodeDetailAtOffset(activeTab.id, offset, true, 'formatted-json'),
    onCopyRightKey: (offset: number) => copyNodeDetailAtOffset(activeTab.id, offset, true, 'key'),
    onCopyRightPath: (offset: number) => copyNodeDetailAtOffset(activeTab.id, offset, true, 'path'),
    onCopyRightValue: (offset: number) => copyValueAtOffset(activeTab.id, offset, true),
    onDeleteRightValue: (offset: number) => applyRightNodeMutationAtOffset(activeTab.id, offset, true, 'delete-node'),
    onEditRightValue: (offset: number) => handleOpenEditNodeAtOffset(activeTab.id, offset, true),
    onLeftChange: handleLeftChange,
    onLeftMount: handleLeftMount,
    onLeftReplace: replaceLeftMatch,
    onLeftReplaceAll: replaceAllLeftMatches,
    onLeftReplaceValueChange: setLeftReplaceText,
    onLeftSearchOptionsChange: handleLeftSearchOptionsChange,
    onLeftSearchTermChange: handleLeftSearchTermChange,
    onLoadMoreLeftSearch: loadMoreLeftSearch,
    onLoadMoreRightSearch: loadMoreRightSearch,
    onLocateRightOffset: (offset: number) => requestWorkerLocate(activeTab.id, offset),
    onOpenRightFind: openRightFind,
    onPinCurrentRightPath: pinActiveRightPath,
    onRenameRightKey: (offset: number) => applyRightNodeMutationAtOffset(activeTab.id, offset, true, 'rename-node-key'),
    onSelectRightPinnedPath: selectRightPinnedPath,
    onSelectRightRecentSearch: (value: string) => {
      setRightSearchTerm(value);
      setRightMatchIndex(0);
      setIsRightFindOpen(true);
      rememberRightSearchTerm(value);
    },
    onUnescapeRightValue: (offset: number) => handleOpenUnescapedNodeAtOffset(activeTab.id, offset, true),
    onPrevLeft: gotoPrevLeft,
    onPrevRight: gotoPrevRight,
    onNextLeft: gotoNextLeft,
    onNextRight: gotoNextRight,
    onRightCollapsedLinesChange: (lines: number[]) => {
      setLargeViewerCollapsedLinesByTab((current: Record<string, number[]>) => ({
        ...current,
        [activeTab.id]: lines,
      }));
    },
    onRightMatchCountChange: setLargeViewerMatchCount,
    onRightMount: handleRightMount,
    onRightSearchOptionsChange: handleRightSearchOptionsChange,
    onRightSearchTermChange: handleRightSearchTermChange,
    t,
  };
}

export function createJsonToolContextMenusProps(input: JsonToolWorkspaceInput) {
  return {
    applyRightNodeMutationAtOffset: input.applyRightNodeMutationAtOffset,
    copyLeftEditorSelection: input.copyLeftEditorSelection,
    copyNodeDetailAtOffset: input.copyNodeDetailAtOffset,
    copyValueAtOffset: input.copyValueAtOffset,
    cutLeftEditorSelection: input.cutLeftEditorSelection,
    handleOpenEditNodeAtOffset: input.handleOpenEditNodeAtOffset,
    handleOpenUnescapedNodeAtOffset: input.handleOpenUnescapedNodeAtOffset,
    isDarkMode: input.isDarkMode,
    leftEditorContextMenu: input.leftEditorContextMenu,
    pasteIntoLeftEditor: input.pasteIntoLeftEditor,
    rightEditorContextMenu: input.rightEditorContextMenu,
    selectAllLeftEditorText: input.selectAllLeftEditorText,
    setLeftEditorContextMenu: input.setLeftEditorContextMenu,
    setRightEditorContextMenu: input.setRightEditorContextMenu,
    shouldUseDedicatedLeftViewer: input.shouldUseDedicatedLeftViewer,
    shouldUseDedicatedRightViewer: input.shouldUseDedicatedRightViewer,
    t: input.t,
    toggleRightFoldAtOffset: input.toggleRightFoldAtOffset,
  };
}
